import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({});

export async function generateAiContent(prompt: string) {
  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents: prompt,
  });

  if (!response.text) {
    throw new Error("No text generated by Gemini.");
  }

  return response.text;
}
